#!/usr/bin/python3
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>This is a CGI script...</title>')
print ('</head>')
print ('<body>')
print ('<h2>Created by E & J & K aka "But first, coffee" </h2>')
print ('</body>')
print ('</html>')